spring:
  application:
    name: chat-platform
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  lifecycle:
    timeout-per-shutdown-phase: 30s
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${SPRING_DATASOURCE_USERNAME:chatuser}
    password: ${SPRING_DATASOURCE_PASSWORD:chatpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chatdb}
      auto-index-creation: false
    
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.in.flight.requests.per.connection: 1
        enable.idempotence: true
        retries: 3
        request.timeout.ms: 30000
        delivery.timeout.ms: 60000
    consumer:
      group-id: chat-platform
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.chatplatform.model"
        session.timeout.ms: 30000
        heartbeat.interval.ms: 3000
    admin:
      properties:
        request.timeout.ms: 30000
        connections.max.idle.ms: 30000
      fail-fast: false

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey-changeInProduction-veryLongRandomString123456789}
    expiration: ${JWT_EXPIRATION:14400000} # 4 hours (reduced from 24h)
    issuer: ${JWT_ISSUER:chat-platform-backend}
    audience: ${JWT_AUDIENCE:chat-platform-users}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@chatplatform.com}
    password: ${ADMIN_PASSWORD:admin123}
    displayName: ${ADMIN_DISPLAY_NAME:System Administrator}
  

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.chatplatform: ${LOG_LEVEL_APP:DEBUG}